name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:v4.18.0
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"
        shell: bash
      - name: run `lake update` to retrieve Zipperposition executable
        run: lake update
        shell: bash
      - uses: leanprover/lean-action@v1
